### ISSUE TITLE
Reference bundle for 38

### ISSUE THREAD

**Issue by W4RJ4** [ICGC-TCGA-PanCancer/CGP-Somatic-Docker#15]
Hi, I have a question regarding this workflows ability to work with 38 reference files? And if it's possible to run it with them, where i can find reference bundles for 38, or if you can point me to the method or tool that was used to generate these existing 37 reference bundles. Thanks.

**Comment by keiranmraine** [comment]
Please see the version with ongoing support at https://github.com/cancerit/dockstore-cgpwgs

We hope to have the GRCh38 reference bundle out very soon.  Feel free to raise an issue on that repository and I will ensure you are notified.

The version of BRASS in this frozen version will not be able to process GRCh38.
